-- Seed portfolio data
INSERT INTO company_profile.portfolio (
    title, 
    slug, 
    short_description, 
    description, 
    cover_image, 
    gallery_images, 
    category, 
    client_name, 
    year, 
    technologies, 
    project_url, 
    github_url, 
    demo_url, 
    featured, 
    status
) VALUES 
(
    'E-Commerce Platform',
    'ecommerce-platform',
    'Modern e-commerce platform built with Next.js and Supabase',
    'A full-featured e-commerce platform with user authentication, product management, shopping cart, and payment integration. Built with modern technologies for optimal performance and user experience. Features include user registration, product catalog, shopping cart, order management, and admin dashboard.',
    '/Portfolio1.png',
    ARRAY['/Portfolio1.png', '/Portfolio2.png'],
    'Web Development',
    'TechCorp Inc.',
    2024,
    ARRAY['Next.js', 'React', 'TypeScript', 'Supabase', 'Tailwind CSS'],
    'https://ecommerce.example.com',
    'https://github.com/username/ecommerce-platform',
    'https://demo-ecommerce.example.com',
    true,
    'published'
),
(
    'Mobile Banking App',
    'mobile-banking-app',
    'Secure mobile banking application for iOS and Android',
    'A comprehensive mobile banking application featuring secure authentication, account management, fund transfers, and real-time notifications. Built with React Native for cross-platform compatibility. Includes biometric authentication, transaction history, and push notifications.',
    '/Portfolio2.png',
    ARRAY['/Portfolio2.png', '/Portfolio3.png'],
    'Mobile Development',
    'BankSecure',
    2024,
    ARRAY['React Native', 'TypeScript', 'Firebase', 'Redux'],
    'https://banking.example.com',
    'https://github.com/username/mobile-banking',
    'https://demo-banking.example.com',
    true,
    'published'
),
(
    'Corporate Website',
    'corporate-website',
    'Professional corporate website with modern design',
    'A responsive corporate website showcasing company services, team members, and contact information. Features modern animations and optimized for search engines. Includes service pages, team profiles, and contact forms.',
    '/Portfolio3.png',
    ARRAY['/Portfolio3.png', '/Portfolio4.png'],
    'Web Development',
    'Business Solutions Ltd.',
    2023,
    ARRAY['HTML5', 'CSS3', 'JavaScript', 'Bootstrap'],
    'https://business.example.com',
    'https://github.com/username/corporate-website',
    'https://demo-business.example.com',
    false,
    'published'
),
(
    'API Management System',
    'api-management-system',
    'RESTful API management and documentation platform',
    'A comprehensive API management system with authentication, rate limiting, analytics, and interactive documentation. Built with Node.js and Express for scalability. Features include API key management, usage analytics, and Swagger documentation.',
    '/Portfolio4.png',
    ARRAY['/Portfolio4.png', '/Portfolio5.png'],
    'Backend Development',
    'DataFlow Systems',
    2023,
    ARRAY['Node.js', 'Express.js', 'MongoDB', 'Redis'],
    'https://api.example.com',
    'https://github.com/username/api-management',
    'https://demo-api.example.com',
    false,
    'published'
),
(
    'Portfolio Website',
    'portfolio-website',
    'Personal portfolio website with modern design',
    'A stunning portfolio website featuring smooth animations, responsive design, and modern UI/UX principles. Built with Next.js and Framer Motion. Includes project showcase, skills section, and contact forms.',
    '/Portfolio5.png',
    ARRAY['/Portfolio5.png', '/Portfolio1.png'],
    'Web Development',
    'Freelance Client',
    2024,
    ARRAY['Next.js', 'React', 'Framer Motion', 'Tailwind CSS'],
    'https://portfolio.example.com',
    'https://github.com/username/portfolio-website',
    'https://demo-portfolio.example.com',
    true,
    'published'
),
(
    'Task Management App',
    'task-management-app',
    'Collaborative task management application',
    'A team collaboration tool for managing tasks, projects, and deadlines. Features include real-time updates, team chat, file sharing, and progress tracking. Built with modern web technologies for seamless collaboration.',
    '/Portfolio1.png',
    ARRAY['/Portfolio1.png', '/Portfolio2.png'],
    'Web Development',
    'TeamWorks Inc.',
    2024,
    ARRAY['Vue.js', 'Node.js', 'PostgreSQL', 'Socket.io'],
    'https://tasks.example.com',
    'https://github.com/username/task-manager',
    'https://demo-tasks.example.com',
    false,
    'published'
),
(
    'Weather Dashboard',
    'weather-dashboard',
    'Real-time weather information dashboard',
    'A weather dashboard application that displays current weather conditions, forecasts, and historical data. Features include location-based weather, multiple city support, and interactive charts. Integrates with multiple weather APIs.',
    '/Portfolio2.png',
    ARRAY['/Portfolio2.png', '/Portfolio3.png'],
    'Web Development',
    'WeatherTech',
    2023,
    ARRAY['React', 'Chart.js', 'OpenWeather API', 'CSS3'],
    'https://weather.example.com',
    'https://github.com/username/weather-dashboard',
    'https://demo-weather.example.com',
    false,
    'published'
),
(
    'Inventory Management System',
    'inventory-management-system',
    'Comprehensive inventory tracking solution',
    'A full-featured inventory management system for businesses to track products, manage stock levels, and generate reports. Features include barcode scanning, low stock alerts, and detailed analytics.',
    'Portfolio3.png',
    ARRAY['Portfolio3.png', 'Portfolio4.png'],
    'Backend Development',
    'Retail Solutions',
    2023,
    ARRAY['Laravel', 'PHP', 'MySQL', 'Bootstrap'],
    'https://inventory.example.com',
    'https://github.com/username/inventory-system',
    'https://demo-inventory.example.com',
    false,
    'published'
);


